CMSgov/AB2D-Libs

- .github/dependabot.yml
Switch dependabot from Maven to Gradle to try to detect issues.
> Switch Dependabot to Gradle

- .github/dependabot.yml
[AB2D-4309](https://jira.cms.gov/browse/AB2D-4309) - Run dependabot weekly
> Run dependabot weekly instead of daily

- .github/workflows/gitleaks.yml
- ab2d-aggregator/build.gradle
- build.gradle
Updates
* Hapi FHIR
* Spring Boot
* NewRelic
* Github Actions Checkout
* SonarQube plugin
* JFrog Plugin
* Testcontainers
> Feature/ab2d-4309 Catch Up Dependabot PR

- build.gradle
[AB2D-4311](https://jira.cms.gov/browse/AB2D-4311) - Jacoco Test Coverage Report Failing/Missing
Add Jacoco XML report to standard build steps so SonarQube can analyze it and pass/fail a build.
> build test report for every subproject

- ab2d-aggregator/README.md
- ab2d-aggregator/build.gradle
- ab2d-aggregator/src/main/java/gov/cms/ab2d/aggregator/ClaimsStream.java
- ab2d-aggregator/src/test/java/gov/cms/ab2d/aggregator/AggregatorCallableTest.java
- ab2d-aggregator/src/test/java/gov/cms/ab2d/aggregator/ClaimsStreamTest.java
- ab2d-aggregator/src/test/java/gov/cms/ab2d/aggregator/FileUtilsTest.java
[AB2D-4258](https://jira.cms.gov/browse/AB2D-4258) - Comments received when doing PR for the merge of this functionality into AB2D
Renamed BeneficiaryStream class to ClaimsStream as it's more descriptive of what it actually is and and added more tests to FileUtilsTest to make sure it did not put any weird characters into the combined file, made sure to include new lines in the test.
Once this is approved and merged, it will create a version 1.1
AB2D main repository will have to be updated with the new library version changes.
None
> Renamed BeneficiaryStream and added more tests to FileUtilsTest

- .github/workflows/gitleaks.yml
- .gitignore
[AB2D-4468](https://jira.cms.gov/browse/AB2D-4468) - Description
- Update github actions
[AB2D-41](https://jira.cms.gov/browse/AB2D-41) - Reason it's related
> Update Github Actions

- build.gradle
> Update but ab2d and libs to the same version of spring

- ab2d-bfd/src/main/resources/application.bfd.properties
- ab2d-bfd/src/test/java/gov/cms/ab2d/bfd/client/BFDClientConfigurationTest.java
- build.gradle
[AB2D-4531](https://jira.cms.gov/browse/AB2D-4531) - Description
Fix issues with dependabot upgrades to spring starter. This will end up creating a new ab2d-bfd library to be used by ab2d
> Spring 2.6.6 update

- ab2d-filters/src/main/java/gov/cms/ab2d/filter/EOBLoadUtilities.java
- ab2d-filters/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerR4.java
- ab2d-filters/src/test/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerR4Test.java
- ab2d-filters/src/test/resources/eobdata/EOB-for-Carrier-R4.json
- ab2d-filters/src/test/resources/eobdata/EOB-for-DME-R4.json
- ab2d-filters/src/test/resources/eobdata/EOB-for-HHA-R4.json
- ab2d-filters/src/test/resources/eobdata/EOB-for-Hospice-R4.json
- ab2d-filters/src/test/resources/eobdata/EOB-for-Inpatient-R4.json
- ab2d-filters/src/test/resources/eobdata/EOB-for-Outpatient-R4.json
- ab2d-filters/src/test/resources/eobdata/EOB-for-SNF-R4.json
- build.gradle
[AB2D-4623](https://jira.cms.gov/browse/AB2D-4623) - Add moved fields in R4
[AB2D-4624](https://jira.cms.gov/browse/AB2D-4624) - Reallow some fields in R4 in filter lib
There were a few new fields in R4 that we had been filtering out of the abundance of caution. We verified that these were okay fields so we put them back in. This is essentially Present on Admission for a diagnosis.
There was also a situation where fields which we provided in STU3 were moved to another location in R4 so that if the PDP moved to R4, they would be losing access to that information. We exposed that data in their new place. For example, **Pricing State Code** moved from:
```
eob.item[N].locationCodeableConcept.extension[N].valueCoding.code
```
to
``` …
```
> Fixes for R4 data issues

- ab2d-filters/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerR4.java
- ab2d-filters/src/test/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerR4Test.java
- build.gradle
[AB2D-4624](https://jira.cms.gov/browse/AB2D-4624) - Not really the right ticket but related and I didn't have a pull request associated with this ticket.
[AB2D-4623](https://jira.cms.gov/browse/AB2D-4623) - The original ticket to add the EOB R4 items.
When I originally create an extension list for eob, I used the copy.setExtension(benefit.getExtensionsByUrl(String)) but getExtensionByUrl creates an unmodifiable list so that if later, we want to add other extensions (such as MIBs in ab2d) it fails. Fixed this and created a test to see if you could add an extension and it prevered the one you originally added.
Here's the method that caused all the trouble in DomainResource:
```
public List<Extension> getExtensionsByUrl(String theUrl) { …
```
> Accidentally created an unmodifiable extension list

- ab2d-aggregator/build.gradle
- build.gradle
Quick fix. Noticed that aggregator wasn't versioned the same way so fixed that.
> Update aggregator version

- build.gradle
> Dependabot fixes

- README.md
- ab2d-events-client/README.md
- build.gradle
[AB2D-5068](https://jira.cms.gov/browse/AB2D-5068)
Update event readme to be more clear
Grammer errors, ways to make readme to be more clear
> Update Readme for events

- ab2d-metrics-lambda/src/main/java/gov/cms/ab2d/metrics/CloudwatchEventHandler.java
- build.gradle
[AB2D-5076](https://jira.cms.gov/browse/AB2D-5076) - Description
Deploy lambda to prod
Update event sqs name to use the new format. 
Simplify the code.
> updated event name, simplified code, updated version

- ab2d-filters/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerR4.java
- ab2d-filters/src/test/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerR4Test.java
- build.gradle
[AB2D-5209](https://jira.cms.gov/browse/AB2D-5209) - Description
Remove provider from r4. This information is already not provided by r3. 
Remove provider from r4. This information is already not provided by r3.
> remove provider from r4, update version

- ab2d-aggregator/build.gradle
- build.gradle
[AB2D-5237](https://jira.cms.gov/browse/AB2D-5237) - Description
Combine Dependabot PRs
Combines Dependabot PRs
> bump up version

- build.gradle
[AB2D-5298](https://jira.cms.gov/browse/AB2D-5298) - Dependabot updates
Keep stuff up to date
> Dependabot updates

- ab2d-events-client/build.gradle
- ab2d-properties-client/build.gradle
- ab2d-sns-client/build.gradle
- build.gradle
[AB2D-5309](https://jira.cms.gov/browse/AB2D-5309) - Description Dependabot Update
Modify modelmapper to work with newer version and dependabot updates
> dependency update

- build.gradle
> Update version of client lib

- ab2d-events-client/build.gradle
- ab2d-sns-client/build.gradle
- build.gradle
[AB2D-5373](https://jira.cms.gov/browse/AB2D-5373)- Dependabot Update
Dependabot Update
> AB2D-5373 dependabot update

- ab2d-sns-client/src/main/java/gov/cms/ab2d/snsclient/clients/SNSConfig.java
- build.gradle
[AB2D-5393](https://jira.cms.gov/browse/AB2D-5393) - Description
Fix bug with coverage count
Fix bug with coverage count
> only use injected sns url locally

- ab2d-properties-client/build.gradle
- ab2d-sns-client/build.gradle
- build.gradle
[AB2D-42](https://jira.cms.gov/browse/AB2D-42) - Description
[AB2D-41](https://jira.cms.gov/browse/AB2D-41) - Reason it's related
> Ktlo dependabot pr changes

- build.gradle
See https://discuss.gradle.org/t/gradle-unable-to-properly-authenticate-against-artifactory/33314/7
[AB2D-5501](https://jira.cms.gov/browse/AB2D-5501) - Work with Devops on terraform deployment issue
> AB2D-5501 Set basic auth for maven

- ab2d-sns-client/build.gradle
- build.gradle
[AB2D-5480](https://jira.cms.gov/browse/AB2D-5480)
Dependabot updates for this sprint for AB2D-Libs repository.
Bumped library versions.
> [Ab2d-5480] AB2D-LIBS Dependabot Updates

- .github/pull_request_template.md
[AB2D-5519](https://jira.cms.gov/browse/AB2D-5519) - PR Templates - Security Section
Adds standard security section to pull request template.
>  AB2D-5519: PR Templates - Security Section

- ab2d-properties-client/build.gradle
- ab2d-sns-client/build.gradle
- build.gradle
https://jira.cms.gov/browse/AB2D-5553
Dependabot updates consolidated PR.
Dependabot updates - Double check pipeline runs successfully.
> [AB2D-5553] PI-4 Sprint 3 Dependabot updates

- ab2d-filters/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerSTU3.java
https://jira.cms.gov/browse/AB2D-5727
Added extension section in AB2D-Libs/ExplanationOfBenefitTrimmerSTU3 
One of our PDP enquired with us about some values that are under extension section in outgoing json for STU3  
Tested manually on local environment
> AB2D-5727 Data Filtering for Humana

- build.gradle
https://jira.cms.gov/browse/AB2D-xxx
filtersVersion was updated from 1.8.6 to 1.8.7
We added extensions for Humana in AB2D-Libs/filters
Unit tests should pass
- [x ] This PR adds a new software dependency or dependencies.
> bump filtersVersion

- ab2d-bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDSearchImpl.java
- ab2d-filters/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerSTU3.java
- build.gradle
https://jira.cms.gov/browse/AB2D-5892
(What was added, updated, or removed in this PR.)
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
> Ab2d-5892/Centene customer support to provide 2 year data

- ab2d-bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDSearchImpl.java
- build.gradle
https://jira.cms.gov/browse/AB2D-5892
Added +1 month for S4802
Bumped bfd version
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
> AB2D-5892/Centene support

- build.gradle
https://jira.cms.gov/browse/AB2D-6054
(What was added, updated, or removed in this PR.)
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
> [AB2D-6054] Temporarily ignore coverage on workaround

- ab2d-events-client/src/main/java/gov/cms/ab2d/eventclient/clients/SQSConfig.java
- build.gradle
https://jira.cms.gov/browse/AB2D-6054
Added a region and credentials provider to SQSConfig
Necessary to fix IMDSV2 requirement Issues
Built locally. To be deployed to IMPL environment for proper testing.
> [Ab2d-6054] Set SQS aws region and credentials provider

- build.gradle
https://jira.cms.gov/browse/AB2D-6054
exclude coverage for config files
Necessary to troubleshoot IMDSV2 Issues. I do not believe these lines are testable in their current form.
> [AB2D-6054] Exclude coverage for Configs

- ab2d-events-client/src/main/java/gov/cms/ab2d/eventclient/clients/SQSConfig.java
- build.gradle
https://jira.cms.gov/browse/AB2D-6054
Change to DefaultProviderChain
(Background context, more in-depth details of the implementation, and anything else you'd like to call out or ask reviewers.)
> [AB2D-6054] Set default provider chain

- Jenkinsfile
This is to update the jdk version to 17
> Fix jdk version from 13 to 17

- ab2d-events-client/src/test/java/gov/cms/ab2d/eventclient/config/AB2DLocalstackContainer.java
- ab2d-events-client/src/test/java/gov/cms/ab2d/eventclient/config/SendSqsEventTest.java
- build.gradle
https://jira.cms.gov/browse/AB2D-6132
https://jira.cms.gov/browse/PLT-438 
Modify the localstack container to use dynamic endpoint strategy for SQS.
Modifies tests to utilize new endpoint strategy
This should fix network related issues we were seeing on the pipeline when spinning up and running tests via testcontainers.
Will test until pipeline passes test conditions
> [AB2D-6132, PLT-438] Modify container with dynamic endpoint strategy

- ab2d-bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDClient.java
- ab2d-bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDClientImpl.java
- ab2d-bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDSearch.java
- ab2d-bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDSearchImpl.java
- ab2d-bfd/src/test/java/gov/cms/ab2d/bfd/client/BlueButtonClientSTU3Test.java
- ab2d-filters/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerSTU3.java
- build.gradle
https://jira.cms.gov/browse/AB2D-6102
- Supported a new OffsetDateTime until parameter in the BFDSearch interface and the corresponding class;
- Supported a new OffsetDateTime until parameter in the ​​BFDClient interface;
Time interval based query for AB2D API
Unit tests updated and passed
> Ab2d-6102/tibq ab2d libs

- ab2d-bfd/src/test/java/gov/cms/ab2d/bfd/client/BFDClientConfigurationTest.java
- ab2d-bfd/src/test/java/gov/cms/ab2d/bfd/client/BFDSearchImplTest.java
- ab2d-bfd/src/test/java/gov/cms/ab2d/bfd/client/BlueButtonClientR4Test.java
- ab2d-bfd/src/test/java/gov/cms/ab2d/bfd/client/BlueButtonClientSTU3Test.java
- ab2d-bfd/src/test/java/gov/cms/ab2d/bfd/client/MockUtils.java
- build.gradle
https://jira.cms.gov/browse/AB2D-6145
- Addresses code smells in tests
- Adds `BFDSearchImplTest` to provide code coverage for `BFDSearchImpl`
- Removes `BFDSearchImpl` from sonarqube excludes
Just this PR won't budge code coverage by much, but it took me forever to write so I want to chunk of my PRs appropriately.
> [AB2D-6145] increase `ab2d-bfd` code coverage

- ab2d-bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDSearchImpl.java
- ab2d-filters/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerSTU3.java
- build.gradle
https://jira.cms.gov/browse/AB2D-6247
Removed 2 month interval for S5884
Humana downloaded the all data that they needed and ask to remove 2 month adjustments that affects their regular jobs
> Ab2 d 6247/remove 2 month humana

- ab2d-events-client/build.gradle
- ab2d-filters/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerSTU3.java
- build.gradle
https://jira.cms.gov/browse/AB2D-6270
Upgraded org.postgresql:postgresql version
Snyk is reporting security vulnerabilities across AB2D repositories
> Ab2d-6270/snyk

- ab2d-events-client/build.gradle
- ab2d-fhir/src/main/java/gov/cms/ab2d/fhir/IdentifierUtils.java
- build.gradle
https://jira.cms.gov/browse/AB2D-6269
Updates spring web version to 5.3.26 to address a vulnerability.
Removes extra spaces in IdentifierUtils to fix a checkstyle violation
Note: 5.3.26 still is flagged for having some vulnerabilities. In order to resolve fully, we would need to go to version 6.1.X. This is not currently possible without a major springboot version change to 3.0.0+
Note: This updates eventsclient version to 1.12.10
Addresses a critical snyk vulnerability
Deployed to lower environments and tested
> [AB2D-6269] Update Spring Web Version

- ab2d-filters/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerSTU3.java
- build.gradle
https://jira.cms.gov/browse/AB2D-6106
Downgraded `hapi` version for the compatibility
> Ab2 d 6106/snyk2

- ab2d-bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDClient.java
- ab2d-bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDClientImpl.java
- ab2d-bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDSearch.java
- ab2d-bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDSearchImpl.java
- ab2d-bfd/src/test/java/gov/cms/ab2d/bfd/client/BFDSearchImplTest.java
- ab2d-bfd/src/test/java/gov/cms/ab2d/bfd/client/BlueButtonClientSTU3Test.java
- ab2d-bfd/src/test/java/gov/cms/ab2d/bfd/client/FhirBfdServerTest.java
- ab2d-filters/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerSTU3.java
- build.gradle
https://jira.cms.gov/browse/AB2D-6291
Supported a new OffsetDateTime until parameter in the BFDSearch interface and the corresponding class;
Supported a new OffsetDateTime until parameter in the ​​BFDClient interface;
Downgraded hapi version (again) because ab2d fails with exception if version is higher
PR is almost a duplicate for https://github.com/CMSgov/AB2D-Libs/pull/382 that I had to revert due to the customization for Humana.
Time interval based query for AB2D API
> Ab2d-6291/tibq final version

- ab2d-bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDClientImpl.java
- ab2d-bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDSearchImpl.java
- ab2d-filters/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerSTU3.java
- build.gradle
https://jira.cms.gov/browse/AB2D-6276
Added logging for HttpPost requests to BFD
2024-12-13T10:31:09.557-08:00  INFO 22019 --- [    Test worker] gov.cms.ab2d.bfd.client.BFDSearchImpl    : Executing BFD Search Request POST http://localhost:60775/v1/fhir/ExplanationOfBenefit/_search HTTP/1.1
> Ab2d-6276/logging for post request

- ab2d-filters/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerSTU3.java
- build.gradle
https://jira.cms.gov/browse/AB2D-6463
Upgraded bfdVersion to 3.2.0 to support HttpPost request with Spring boot upgrade
> Spring update support http post

- ab2d-bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDClientImpl.java
- ab2d-bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDSearchImpl.java
- ab2d-bfd/src/test/java/gov/cms/ab2d/bfd/client/BlueButtonClientR4Test.java
- ab2d-bfd/src/test/java/gov/cms/ab2d/bfd/client/BlueButtonClientSTU3Test.java
- ab2d-bfd/src/test/java/gov/cms/ab2d/bfd/client/MockUtils.java
- ab2d-filters/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerSTU3.java
- build.gradle
https://jira.cms.gov/browse/...
Revert Post request to BFD
> Revert ab2d 6276

- .github/workflows/build.yaml
- .github/workflows/publish.yaml
https://jira.cms.gov/browse/...
> PLT-833 test ab2d-libs workflows

- .github/workflows/publish.yml
- build.gradle
Temp fix for publishing snapshots
> Temp fix for publishing snapshots

- .github/workflows/publish.yml
- ab2d-contracts-client/src/main/java/gov/cms/ab2d/contracts/model/Contract.java
- build.gradle
https://jira.cms.gov/browse/AB2D-6862
- Update Contract data model to use sequence generator
The HPMS sync job is failing when adding a new contract:
```
org.quartz.SchedulerException: Job threw an unhandled exception.
at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet [ERROR: relation \"contract_seq\" does not exist
Position: 16] [select nextval('contract_seq')]; SQL [select nextval('contract_seq')]
at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:277)
at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossibl …
```
> AB2D-6862 Update Contract data model to use sequence generator
